### ISSUE TITLE
Wrong aspect ratio on kz_wetbricks

### ISSUE THREAD

**Issue by Szwagi** [KZGlobalTeam/map-images#24]
it's a square, noticed it breaking kzstats, but maybe it's up to the developers to not assume the aspect ratio of the images.

**Comment by Sikarii** [comment]
I kind of agree that I expect all the images to be the same size when fetching them from here, so perhaps they could be forcibly resized for our desired aspect ratio.

P.S. KZStats does not use this repository for images.

**Comment by Sikarii** [comment]
This is now resolved from #26, lemme know if there's anymore issues.
